[package]
name = "fge_models"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { workspace = true }
fixtures = "2"
mlua = { version = "0.11.4", features = ["lua54", "serde", "vendored"] }
bevy_reflect = "0.17.2"
fge_input = { path = "../fge_input" }

[build-dependencies]
fixtures = "2"
